// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUPkcwRUeM_I9FYw-quAcXOkkSjfmEDqc',
    appId: '1:244348838509:web:1deaed7158aab731cfd564',
    messagingSenderId: '244348838509',
    projectId: 'lapis-1aed6',
    authDomain: 'lapis-1aed6.firebaseapp.com',
    storageBucket: 'lapis-1aed6.appspot.com',
    measurementId: 'G-TEZ2KTVKK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhiBNlFzNbYBibov6ezpUVFUyvE_QgChc',
    appId: '1:244348838509:android:28dffe619db47598cfd564',
    messagingSenderId: '244348838509',
    projectId: 'lapis-1aed6',
    storageBucket: 'lapis-1aed6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBae0B2UNWRnWZN4n4JhtOyXHccTtUMkLA',
    appId: '1:244348838509:ios:ab6568ebe707fe57cfd564',
    messagingSenderId: '244348838509',
    projectId: 'lapis-1aed6',
    storageBucket: 'lapis-1aed6.appspot.com',
    androidClientId: '244348838509-1opmljej5vdncgqrnbo1kkvgbqcn5a7u.apps.googleusercontent.com',
    iosClientId: '244348838509-etdpu8mtmnqqt1fd6iaa0ip0lrt6h74a.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
